[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "adunblock-server-tag-django"
version = "1.0.0"
description = "A Django package to fetch and render scripts from a remote URL with template tag integration and caching support."
readme = "README.md"
license = {text = "ISC"}
authors = [
    {name = "Adunblock", email = "dev@adunblock.com"}
]
keywords = ["django", "python", "server-tag", "script-loading", "remote-scripts", "template-tags"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 3.2",
    "Framework :: Django :: 4.0",
    "Framework :: Django :: 4.1",
    "Framework :: Django :: 4.2",
    "Framework :: Django :: 5.0",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: ISC License (ISCL)",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10", 
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
requires-python = ">=3.8"
dependencies = [
    "Django>=3.2",
    "requests>=2.25.0",
]

[project.urls]
Homepage = "https://github.com/adunblock/adunblock-server-tag"
Repository = "https://github.com/adunblock/adunblock-server-tag"
Issues = "https://github.com/adunblock/adunblock-server-tag/issues"

[tool.setuptools.packages.find]
include = ["server_tag*"]

[tool.setuptools.package-data]
server_tag = ["templatetags/*.py"]